/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redsocialproyecctoii;
import javax.swing.JOptionPane;
import redsocialproyecctoii.Master;
/**
 *
 * @author Hp
 */
public class EditarMiPerfil extends javax.swing.JFrame {
public Master mas;
    /**
     * Creates new form EditarMiPerfil
     */
    public EditarMiPerfil(Master mast) {
        initComponents();
        mas=mast;
        this.setTitle("Editar Tu Perfil ");
        setLocationRelativeTo(null);
        
        TxtNombre.setText(mas.UsuarioActual.getNombre());
        TxtUser.setText(mas.UsuarioActual.getUser());
        TxtPass.setText(mas.UsuarioActual.getPass());
        EdadSpin.setValue(mas.UsuarioActual.getAge());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        edadSpin = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Return = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtNombre = new javax.swing.JTextField();
        TxtUser = new javax.swing.JTextField();
        TxtPass = new javax.swing.JPasswordField();
        EdadSpin = new javax.swing.JSpinner();
        EDITAR = new javax.swing.JButton();
        btnDesActivar = new javax.swing.JButton();

        jLabel3.setText("Usuario");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));

        Return.setBackground(new java.awt.Color(0, 51, 153));
        Return.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        Return.setText("<");
        Return.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnMouseClicked(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("Editar Perfil");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(Return, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTitulo)
                    .addComponent(Return))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel1.setText("Nombre");

        jLabel2.setText("Usuario");

        jLabel4.setText("Contraseña");

        jLabel5.setText("Edad");

        TxtNombre.setText("Nombre");

        TxtUser.setText("User");

        TxtPass.setText("Password");

        EDITAR.setBackground(new java.awt.Color(0, 51, 153));
        EDITAR.setText("Aplicar Cambios");
        EDITAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITARMouseClicked(evt);
            }
        });

        btnDesActivar.setBackground(new java.awt.Color(255, 51, 51));
        btnDesActivar.setText("Desactivar Cuenta");
        btnDesActivar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDesActivarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TxtNombre)
                                .addComponent(TxtUser)
                                .addComponent(TxtPass, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE))
                            .addComponent(EdadSpin, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(EDITAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDesActivar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TxtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(TxtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(EdadSpin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDITAR)
                    .addComponent(btnDesActivar))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnMouseClicked
        MiPerfil mp =new MiPerfil(mas);
        mp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_ReturnMouseClicked

    private void EDITARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITARMouseClicked
        // TODO add your handling code here:
       String name= TxtNombre.getText();
       String user = TxtUser.getText();       
       String password = TxtPass.getText();
       int edad=(Integer) EdadSpin.getValue();
       String oldUser=mas.UsuarioActual.getUser();
       

        
        for (int i = 0; i < mas.NumUsers; i++) {
             if (user.equals(mas.users[i].getUser()) && !user.equals(mas.UsuarioActual.getUser())) {
                JOptionPane.showMessageDialog(null, "El Username: "+user+" ya Existe");
                return;
            }
        }

       
        int confirmar = JOptionPane.showConfirmDialog(null,"¿Desea Aplicar los cambios?", "Confirmacion", JOptionPane.OK_CANCEL_OPTION);
        if (confirmar==0) {
            for (int i = 0; i <mas.NumUsers; i++) {
                if (mas.users[i].equals(mas.UsuarioActual)) {
                    mas.users[i].setUser(user);
                }
            }
            mas.UsuarioActual.setNombre(name);
            mas.UsuarioActual.setUser(user);
            mas.UsuarioActual.setPass(password);
            mas.UsuarioActual.setEdad(edad);
            
          
            //Cambair lista Following de Otros
           for(Usuario u : mas.users){
               if(u==null){
                   break;
               }
               for ( String usr : mas.UsuarioActual.getfollowers()) {
                   if(u==null){
                       break;
                   }
                   if (u.getUser().equals(usr)) {
                       for (int i = 0; i < u.getNumFollowing(); i++) {
                           if (u.getfollowing()[i].equals(oldUser)) {
                               u.UpdateFollowing(user, i);
                           }
                       }
 
                   }
               }
               
           }
           
           //Cambair lista Followers de Otros
           for(Usuario u : mas.users){
               if(u==null){
                   break;
               }
               for ( String usr : mas.UsuarioActual.getfollowers()) {
                   if(u==null){
                       break;
                   }
                   if (u.getUser().equals(usr)) {
                       for (int i = 0; i < u.getNumFollowers(); i++) {
                           if (u.getfollowers()[i].equals(oldUser)) {
                               u.UpdateFollowers(user, i);
                           }
                       }
 
                   }
               }
               
           }
           
           
            
            for (int i = 0; i < mas.NumTweets; i++) {
                if (mas.tweets[i].getUsuario().equals(oldUser)) {
                    mas.tweets[i].setUsuario(user);
                }
            }
           
            MiPerfil mp =new MiPerfil(mas);
            mp.setVisible(true);
            this.dispose();
            
        }
       
    }//GEN-LAST:event_EDITARMouseClicked

    private void btnDesActivarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDesActivarMouseClicked
            int confirmar = JOptionPane.showConfirmDialog(null,"¿Desea desactivar la Cuenta?\nRecuerda que esto Cerrara tu Sesion\nLa Cuenta se Activara cuando vuelvas a Logear", "Atencion", JOptionPane.OK_CANCEL_OPTION);
            if (confirmar==0) {
                 mas.UsuarioActual.DesactivarCuenta();
                 mas.Logout();
                         Inicio in= new Inicio(mas);
                         in.setVisible(true);
                         setLocationRelativeTo(null);
                         this.dispose();
            }

    }//GEN-LAST:event_btnDesActivarMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EDITAR;
    private javax.swing.JSpinner EdadSpin;
    private javax.swing.JButton Return;
    private javax.swing.JTextField TxtNombre;
    private javax.swing.JPasswordField TxtPass;
    private javax.swing.JTextField TxtUser;
    private javax.swing.JButton btnDesActivar;
    private javax.swing.JSpinner edadSpin;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
