/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redsocialproyecctoii;
import javax.swing.ImageIcon;
import redsocialproyecctoii.Master;
/**
 *
 * @author Hp
 */
public class MiPerfil extends javax.swing.JFrame {
        //private Usuario usuario; //reactivar en caso de recuperar la funcion
    private String nombre;
    private String user;
    private String genero;
    private String fecha;
    private int numFollowers;
    private int numFollowing;
    
    public Master mas;
    /**
     * Creates new form MiPerfil
     */
    public MiPerfil(Master mast) {
        initComponents();
        
        mas=mast;
        this.setTitle("Mi Perfil ( @"+mas.getUsuarioActual()+" )");
        setLocationRelativeTo(null);
        
        //Cambiar los Nombres y mostrar los Datos:
        lblUsername.setText("@"+mas.getUsuarioActual());
        lblNombre.setText(mas.UsuarioActual.getNombre());
        lblGenAge.setText(mas.UsuarioActual.getGen()+" "+mas.UsuarioActual.getAge());
        lblFecha.setText(mas.UsuarioActual.getFecha());
        lblFollowers.setText("Followers: "+mas.UsuarioActual.getNumFollowers());
        lblFollowing.setText("Following: "+mas.UsuarioActual.getNumFollowing());
        
        String Ruta="";
        
        if(mas.UsuarioActual.getGen().equalsIgnoreCase("Masculino")){
            Ruta="src/imagen/pfp-Hombre.png";    
        } 
        else if(mas.UsuarioActual.getGen().equalsIgnoreCase("Femenino")){
            Ruta="src/imagen/pfp-mujer.png";  
        }
        Pfp.setIcon(new ImageIcon(Ruta));
          
             
        for (int i =0; i < mas.UsuarioActual.getNumTweetsU(); i++) {
            String MiTimeline=mas.UsuarioActual.getTweets()[i].getTweetInfo() +"\n_______________________\n"+ TxtATweets.getText();
            TxtATweets.setText(MiTimeline);
        }
     //   TxtATweets.setText(mas.UsuarioActual.getTweets().toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblGenAge = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFollowers = new javax.swing.JLabel();
        lblFollowing = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Return = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtATweets = new javax.swing.JTextArea();
        Pfp = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblGenAge.setText("M/F : Edad");

        lblUsername.setText("@Username");

        lblFecha.setText("Fecha de Ingreso");

        lblFollowers.setText("Followers");
        lblFollowers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFollowersMouseClicked(evt);
            }
        });

        lblFollowing.setText("Following");
        lblFollowing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFollowingMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        Return.setBackground(new java.awt.Color(0, 51, 204));
        Return.setText("<- Regresar");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Return)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Return)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        TxtATweets.setEditable(false);
        TxtATweets.setColumns(20);
        TxtATweets.setRows(5);
        jScrollPane1.setViewportView(TxtATweets);

        Pfp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Pfp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/pfp-Hombre.png"))); // NOI18N
        Pfp.setText("FotoPFP");
        Pfp.setMinimumSize(new java.awt.Dimension(318, 241));

        btnEdit.setText("Editar Perfil");
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblGenAge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblFollowing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblUsername, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFecha)
                                    .addComponent(lblFollowers, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(43, 43, 43))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGenAge))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUsername)
                            .addComponent(lblFecha))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFollowing)
                            .addComponent(lblFollowers)))
                    .addComponent(Pfp, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
      
                new Navegacion(mas).setVisible(true);
                 this.dispose();
                 this.setLocationRelativeTo(null);
    }//GEN-LAST:event_ReturnActionPerformed

    private void lblFollowingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFollowingMouseClicked
        // TODO add your handling code here:
                 new MiFollows(mas).setVisible(true);
                 this.dispose();
                 this.setLocationRelativeTo(null);
    }//GEN-LAST:event_lblFollowingMouseClicked

    private void lblFollowersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFollowersMouseClicked
        // TODO add your handling code here:
         new MiFollows(mas).setVisible(true);
                 this.dispose();
                 this.setLocationRelativeTo(null);
    }//GEN-LAST:event_lblFollowersMouseClicked

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
                 new EditarMiPerfil(mas).setVisible(true);
                 this.dispose();
                 this.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnEditMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MiPerfil(mas).setVisible(true);
//            }
//        });
//    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Pfp;
    private javax.swing.JButton Return;
    private javax.swing.JTextArea TxtATweets;
    private javax.swing.JButton btnEdit;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFollowers;
    private javax.swing.JLabel lblFollowing;
    private javax.swing.JLabel lblGenAge;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
