/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redsocialproyecctoii;
import redsocialproyecctoii.Master;

import java.awt.Dimension;
import java.util.Calendar;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

public class Navegacion extends javax.swing.JFrame {
    private String nombre;
    private String usuario;
    private String genero;
    private String fecha;
    private int numFollowers;
    private int numFollowing;
    
    public Master mas;
    
    public Navegacion(Master mast) {
        initComponents();
        mas=mast;
        this.setTitle("TimeLine @"+mas.getUsuarioActual());
        setLocationRelativeTo(null);
        lblNameUser.setText("@"+mas.getUsuarioActual());
        
            for (int i =0; i < mas.NumTweets; i++) {
                String UserTweet=mas.tweets[i].getUsuario(); //extraer quien hizo el tweet(Usuario)
                
                if(UserTweet.equals(mas.UsuarioActual.getUser())){
                    String MiTimeline=mas.tweets[i].getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
                    TimeLine.setText(MiTimeline);
                    //Si soy yo, añadade el Twwet a la Timeline
                }

          
                for (int j = 0; j < mas.UsuarioActual.getNumFollowing(); j++) {  
                    if(UserTweet.equals(mas.UsuarioActual.getfollowing()[j])){ //Si se encuentra en mis followers
                        
                        for (Usuario activos : mas.users) {
                            if(activos==null){
                                break;
                            }
                            if(activos.getUser().equals(mas.UsuarioActual.getfollowing()[j])){
                                if(activos.getEstado()){
                                   String MiTimeline=mas.tweets[i].getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
                                    TimeLine.setText(MiTimeline); 
                                }
                            }      
                        }
                    
                    }
                }                      
        }
    }
    
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        PanelType = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaTweet = new javax.swing.JTextArea();
        btnTwitt = new javax.swing.JButton();
        lblNameUser = new javax.swing.JLabel();
        charsPost = new javax.swing.JLabel();
        PanelBtn = new javax.swing.JPanel();
        btnInteract = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        RefreshTimeline = new javax.swing.JButton();
        PanelSearch = new javax.swing.JPanel();
        txtBusqueda = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ListaBsq = new javax.swing.JTextArea();
        has = new javax.swing.JLabel();
        us = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ListaHash = new javax.swing.JTextArea();
        txtHash = new javax.swing.JTextField();
        btnHashtag = new javax.swing.JButton();
        jlabelpost = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TimeLine = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();

        jPasswordField1.setText("jPasswordField1");

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelType.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        areaTweet.setColumns(20);
        areaTweet.setRows(5);
        areaTweet.setLineWrap(true);
        areaTweet.setWrapStyleWord(true);
        areaTweet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                areaTweetKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                areaTweetKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                areaTweetKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(areaTweet);

        btnTwitt.setText("Publicar");
        btnTwitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTwittActionPerformed(evt);
            }
        });

        lblNameUser.setText("@Username");

        charsPost.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        charsPost.setText("0 / 140");

        javax.swing.GroupLayout PanelTypeLayout = new javax.swing.GroupLayout(PanelType);
        PanelType.setLayout(PanelTypeLayout);
        PanelTypeLayout.setHorizontalGroup(
            PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTypeLayout.createSequentialGroup()
                .addGroup(PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelTypeLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelTypeLayout.createSequentialGroup()
                                .addComponent(lblNameUser)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTypeLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnTwitt))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelTypeLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(charsPost, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelTypeLayout.setVerticalGroup(
            PanelTypeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTypeLayout.createSequentialGroup()
                .addComponent(lblNameUser)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(charsPost)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTwitt)
                .addContainerGap())
        );

        PanelBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnInteract.setText("Interacciones");
        btnInteract.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInteractMouseClicked(evt);
            }
        });

        btnClose.setText("Cerrar Sesion");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnProfile.setText("Mi Perfil");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        RefreshTimeline.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        RefreshTimeline.setText("Refresh Timeline");
        RefreshTimeline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshTimelineMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout PanelBtnLayout = new javax.swing.GroupLayout(PanelBtn);
        PanelBtn.setLayout(PanelBtnLayout);
        PanelBtnLayout.setHorizontalGroup(
            PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClose, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInteract, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RefreshTimeline, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        PanelBtnLayout.setVerticalGroup(
            PanelBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBtnLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(btnProfile)
                .addGap(88, 88, 88)
                .addComponent(btnInteract)
                .addGap(18, 18, 18)
                .addComponent(RefreshTimeline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose)
                .addGap(82, 82, 82))
        );

        PanelSearch.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        txtBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBusquedaActionPerformed(evt);
            }
        });
        txtBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBusquedaKeyReleased(evt);
            }
        });

        btnSearch.setText("🔍");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        ListaBsq.setEditable(false);
        ListaBsq.setColumns(20);
        ListaBsq.setRows(5);
        jScrollPane3.setViewportView(ListaBsq);

        has.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        has.setText("Buscar #Hastag");

        us.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        us.setText("Buscar Usuarios");

        ListaHash.setEditable(false);
        ListaHash.setColumns(20);
        ListaHash.setRows(5);
        jScrollPane4.setViewportView(ListaHash);

        txtHash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHashActionPerformed(evt);
            }
        });
        txtHash.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtHashKeyReleased(evt);
            }
        });

        btnHashtag.setText("🔍");
        btnHashtag.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHashtagMouseClicked(evt);
            }
        });
        btnHashtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHashtagActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSearchLayout = new javax.swing.GroupLayout(PanelSearch);
        PanelSearch.setLayout(PanelSearchLayout);
        PanelSearchLayout.setHorizontalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSearchLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelSearchLayout.createSequentialGroup()
                        .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(txtHash, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnHashtag))
                    .addGroup(PanelSearchLayout.createSequentialGroup()
                        .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelSearchLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(has, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelSearchLayout.createSequentialGroup()
                                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSearchLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(us, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(38, 38, 38)))
        );
        PanelSearchLayout.setVerticalGroup(
            PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSearchLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(has, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHash, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHashtag))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(PanelSearchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PanelSearchLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(us)
                    .addContainerGap(507, Short.MAX_VALUE)))
        );

        jlabelpost.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        TimeLine.setEditable(false);
        TimeLine.setColumns(20);
        TimeLine.setRows(5);
        jScrollPane2.setViewportView(TimeLine);

        javax.swing.GroupLayout jlabelpostLayout = new javax.swing.GroupLayout(jlabelpost);
        jlabelpost.setLayout(jlabelpostLayout);
        jlabelpostLayout.setHorizontalGroup(
            jlabelpostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
        );
        jlabelpostLayout.setVerticalGroup(
            jlabelpostLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jlabelpostLayout.createSequentialGroup()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PanelType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jlabelpost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabelpost, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void areaTweetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaTweetKeyTyped
        if (areaTweet.getText().length() >= 140) {
        evt.consume();
    }
    }//GEN-LAST:event_areaTweetKeyTyped

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
       //BOTON BUSCAR USERS
        String UserOtro=txtBusqueda.getText();
        boolean UsuarioEncontrado=false;
        
        if (UserOtro.equals(mas.UsuarioActual.getUser())) {
        JOptionPane.showMessageDialog(null, "No puedes Buscar tu Propio Usuario");
        return;
        }
       
        for (int i = 0; i < mas.NumUsers; i++) {
            if(UserOtro.equals(mas.users[i].getUser())){
                 for (Usuario activos : mas.users) {
                            if(activos==null){
                                break;
                            }
                            if(activos.getUser().equals(UserOtro)){
                                if(activos.getEstado()){
                                    mas.UsuarioBusqueda=mas.users[i];
                                    PerfilOtro op =new PerfilOtro(mas);
                                    op.setVisible(true);
                                    this.dispose();
                                    UsuarioEncontrado=true;
                                    break;
                                } else if(activos.getEstado()==false){
                                    JOptionPane.showMessageDialog(null, "Esta Cuenta has sido Desactivada");
                                    return;
                                }
                            }      
                        }

            }
        }
        if (!UsuarioEncontrado) {
            JOptionPane.showMessageDialog(null, "No existe un usuario con este Username \n Porfavor verificar Mayusculas o que este escrito correctamente");
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        mas.Logout();
        Inicio in= new Inicio(mas);
        in.setVisible(true);
        setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnTwittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTwittActionPerformed
        //BOTON SUBIR TWEETS
        
        Calendar cal= Calendar.getInstance();
        int dia=cal.get(Calendar.DATE);
        int mes= cal.get(Calendar.MONTH)+1;
        int anio= cal.get(Calendar.YEAR);
        String usr=mas.UsuarioActual.getUser();
        String tweet = areaTweet.getText().trim();
        String fecha = dia+"/"+mes+"/"+anio;
        
        if(!tweet.isEmpty()){
            Tweets newtweet=new Tweets(usr, tweet);
            mas.AgregarTweetsArreglo(newtweet);
            
            String Post=TimeLine.toString();
            String NewTimline=newtweet.getTweetInfo()+"\n"+Post;
           // PanelPost.setText(Post);
            
                   
            String MiTimeline=newtweet.getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
            TimeLine.setText(MiTimeline);
            areaTweet.setText("");
           
            charsPost.setText(areaTweet.getText().length()+"/ 140");
        }
       
    }//GEN-LAST:event_btnTwittActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
        MiPerfil mp =new MiPerfil(mas);
        mp.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_btnProfileActionPerformed

    private void txtBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyPressed
 
    }//GEN-LAST:event_txtBusquedaKeyPressed

    private void areaTweetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaTweetKeyPressed
    
    }//GEN-LAST:event_areaTweetKeyPressed

    private void txtBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBusquedaActionPerformed
          
    }//GEN-LAST:event_txtBusquedaActionPerformed

    private void RefreshTimelineMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshTimelineMouseClicked
        // RETORNAR la timeline al original
        TimeLine.setText("");
        txtHash.setText("");
            for (int i =0; i < mas.NumTweets; i++) {
                String UserTweet=mas.tweets[i].getUsuario();
                
                if(UserTweet.equals(mas.UsuarioActual.getUser())){
                    String MiTimeline=mas.tweets[i].getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
                    TimeLine.setText(MiTimeline);
                }

          
                for (int j = 0; j < mas.UsuarioActual.getNumFollowing(); j++) {  
                    if(UserTweet.equals(mas.UsuarioActual.getfollowing()[j])){
                        
                        for (Usuario activos : mas.users) {
                            if(activos==null){
                                break;
                            }
                            if(activos.getUser().equals(mas.UsuarioActual.getfollowing()[j])){
                                if(activos.getEstado()){
                                  String MiTimeline=mas.tweets[i].getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
                                  TimeLine.setText(MiTimeline);
                                }
                            }      
                        }
                    
                    }
                }                      
        }
    }//GEN-LAST:event_RefreshTimelineMouseClicked

    private void btnInteractMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInteractMouseClicked
        // MOSTRAR MIS MENCIONES
        TimeLine.setText("");
            for (int i =0; i < mas.NumTweets; i++) {
                String TweetInter=mas.tweets[i].getText();
                
                if(TweetInter.contains("@"+mas.UsuarioActual.getUser())){
                    for (Usuario activos : mas.users) {
                            if(activos==null){
                                break;
                            }
                            if(activos.getUser().equals(mas.tweets[i].getUsuario())){
                                if(activos.getEstado()){
                                   String MiTimeline=mas.tweets[i].getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
                                   TimeLine.setText(MiTimeline);
                                }
                            }      
                        }
                    
                }
                      
        }
    }//GEN-LAST:event_btnInteractMouseClicked

    private void areaTweetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_areaTweetKeyReleased
      int charact=areaTweet.getText().length();
        charsPost.setText(charact+"/ 140"); 
        
        if (charact>=140) {
            evt.consume();
            JOptionPane.showMessageDialog(areaTweet, "Solo se permite 140 caracteres. ");
            areaTweet.setText(areaTweet.getText().substring(0, 140));
        }
    }//GEN-LAST:event_areaTweetKeyReleased

    private void txtBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBusquedaKeyReleased
       //LO QUE PASA AL ESCRIBIR EN BUSCAR USUSARIO
       
        ListaBsq.setText("");
        String Buscar=txtBusqueda.getText();
        
            if (Buscar.isEmpty()) {
        return;
    }
            
        StringBuilder resultados = new StringBuilder();
        
        for (int i = 0; i <mas.NumUsers; i++) {
            String username = mas.users[i].getUser();
            
            if (mas.UsuarioActual.getUser().equals(username)) {
                continue;  
        }
            if(mas.users[i].getUser().contains(Buscar)){
                for (Usuario activos : mas.users) {
                            if(activos==null){
                                break;
                            }
                            if(activos.getUser().equals(Buscar)){
                                if(activos.getEstado()){
                                   resultados.append(mas.users[i].getUser()).append("\n");
                                }
                            }      
                        }
            }
        }
        ListaBsq.setText(resultados.toString());
    }//GEN-LAST:event_txtBusquedaKeyReleased

    private void txtHashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHashActionPerformed

    }//GEN-LAST:event_txtHashActionPerformed

    private void btnHashtagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHashtagActionPerformed
        //PONER LOS # EN LA TIMELINE
        
        TimeLine.setText("");
            for (int i =0; i < mas.NumTweets; i++) {
                String TweetHash=mas.tweets[i].getText();
                
                if(TweetHash.contains("#"+txtHash.getText())){
                        for (Usuario activos : mas.users) {
                            if(activos==null){
                                break;
                            }
                            if(activos.getUser().equals(mas.tweets[i].getUsuario())){
                                if(activos.getEstado()){
                                   String MiTimeline=mas.tweets[i].getTweetInfo() +"\n_______________________\n"+ TimeLine.getText();
                                   TimeLine.setText(MiTimeline);
                                }
                            }      
                        }
                    
                }
                      
        }
    }//GEN-LAST:event_btnHashtagActionPerformed

    private void txtHashKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHashKeyReleased
        // ESCRIBIR EN BUSCAR HASHTAG
        ListaBsq.setText("");
        String Hash="#"+txtHash.getText();
        
            if (Hash.isEmpty() || Hash.equals("#")) {
        return;
    }
            
        StringBuilder resultadosH = new StringBuilder();
        
        for (int i = 0; i <mas.NumTweets; i++) {
            String[] Hashtags=mas.tweets[i].getHashtags();
            for (String Hashtag : Hashtags) {
                if (Hashtag.contains(Hash) && !resultadosH.toString().contains(Hashtag)) {
                    resultadosH.append(Hashtag+"\n");
                }
 
            }
        }
        ListaHash.setText(resultadosH.toString());
     
    }//GEN-LAST:event_txtHashKeyReleased

    private void btnHashtagMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHashtagMouseClicked
        
    }//GEN-LAST:event_btnHashtagMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea ListaBsq;
    private javax.swing.JTextArea ListaHash;
    private javax.swing.JPanel PanelBtn;
    private javax.swing.JPanel PanelSearch;
    private javax.swing.JPanel PanelType;
    private javax.swing.JButton RefreshTimeline;
    private javax.swing.JTextArea TimeLine;
    private javax.swing.JTextArea areaTweet;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHashtag;
    private javax.swing.JButton btnInteract;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnTwitt;
    private javax.swing.JLabel charsPost;
    private javax.swing.JLabel has;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel jlabelpost;
    private javax.swing.JLabel lblNameUser;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtHash;
    private javax.swing.JLabel us;
    // End of variables declaration//GEN-END:variables
}