/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package redsocialproyecctoii;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import redsocialproyecctoii.Master;
/**
 *
 * @author Hp
 */
public class PerfilOtro extends javax.swing.JFrame {
        //private Usuario usuario; //reactivar en caso de recuperar la funcion
    private String nombre;
    private String user;
    private String genero;
    private String fecha;
    private int numFollowers;
    private int numFollowing;
    
    public Master mas;
    /**
     * Creates new form MiPerfil
     */
    public PerfilOtro(Master mast) {
        initComponents();
        mas=mast;
        this.setTitle("Perfil de ( @"+mas.UsuarioBusqueda.getUser()+" )");
        setLocationRelativeTo(null);
        
        //Cambiar los Nombres y mostrar los Datos:
        lblUsername.setText("@"+mas.UsuarioBusqueda.getUser());
        lblNombre.setText(mas.UsuarioBusqueda.getNombre());
        lblGenAge.setText(mas.UsuarioBusqueda.getGen()+" "+mas.UsuarioBusqueda.getAge());
        lblFecha.setText(mas.UsuarioBusqueda.getFecha());
        lblFollowers.setText("Followers: "+mas.UsuarioBusqueda.getNumFollowers());
        lblFollowing.setText("Following: "+mas.UsuarioBusqueda.getNumFollowing());
        
        String Ruta="";
        if(mas.UsuarioBusqueda.getGen().equalsIgnoreCase("Masculino")){
            Ruta="src/imagen/PfpMasculino.png";    
        } 
        else if(mas.UsuarioBusqueda.getGen().equalsIgnoreCase("Femenino")){
            Ruta="src/imagen/PfpFemenina.png";  
        }
        pfpO.setIcon(new ImageIcon(Ruta));
             
             
        for (int i =0; i < mas.UsuarioBusqueda.getNumTweetsU(); i++) {
            String MiTimeline=mas.UsuarioBusqueda.getTweets()[i].getTweetInfo() +"\n_______________________\n"+ TxtATweets.getText();
            TxtATweets.setText(MiTimeline);
        }
     //   TxtATweets.setText(mas.UsuarioActual.getTweets().toString());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombre = new javax.swing.JLabel();
        lblGenAge = new javax.swing.JLabel();
        lblUsername = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFollowers = new javax.swing.JLabel();
        lblFollowing = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Return = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TxtATweets = new javax.swing.JTextArea();
        pfpO = new javax.swing.JLabel();
        Seguir = new javax.swing.JButton();
        DejardeSeguir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNombre.setText("Nombre");

        lblGenAge.setText("M/F : Edad");

        lblUsername.setText("@Username");

        lblFecha.setText("Fecha de Ingreso");

        lblFollowers.setText("Followers");
        lblFollowers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFollowersMouseClicked(evt);
            }
        });

        lblFollowing.setText("Following");
        lblFollowing.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFollowingMouseClicked(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));

        Return.setBackground(new java.awt.Color(0, 51, 204));
        Return.setText("<- Regresar");
        Return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Return)
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Return)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        TxtATweets.setEditable(false);
        TxtATweets.setColumns(20);
        TxtATweets.setRows(5);
        jScrollPane1.setViewportView(TxtATweets);

        pfpO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pfpO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/PfpFemenina.png"))); // NOI18N
        pfpO.setMinimumSize(new java.awt.Dimension(318, 241));

        Seguir.setBackground(new java.awt.Color(0, 51, 204));
        Seguir.setText("Seguir");
        Seguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SeguirMouseClicked(evt);
            }
        });

        DejardeSeguir.setBackground(new java.awt.Color(0, 51, 204));
        DejardeSeguir.setText("Dejar de Seguir");
        DejardeSeguir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DejardeSeguirMouseClicked(evt);
            }
        });
        DejardeSeguir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DejardeSeguirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pfpO, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFollowing, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblGenAge, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(24, 24, 24)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblFollowers, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblFecha)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(Seguir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DejardeSeguir, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(56, 56, 56))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Seguir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUsername)
                            .addComponent(DejardeSeguir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(lblFollowing))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFecha)
                                    .addComponent(lblGenAge))
                                .addGap(26, 26, 26)
                                .addComponent(lblFollowers)))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pfpO, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnActionPerformed
                new Navegacion(mas).setVisible(true);
                 this.dispose();
                 this.setLocationRelativeTo(null);
    }//GEN-LAST:event_ReturnActionPerformed

    private void SeguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SeguirMouseClicked
        boolean YaLoSigo=false;
        
        for (int i = 0; i <mas.UsuarioActual.getNumFollowing(); i++) {
            if (mas.UsuarioBusqueda.getUser().equals(mas.UsuarioActual.getfollowing()[i])) {
                YaLoSigo=true;
                break;
            }
        }
                    
            
            if (YaLoSigo) {
                JOptionPane.showMessageDialog(null, "Ya sigues a @"+mas.UsuarioBusqueda.getUser());
                
            }else{
                 mas.agregarFollower();
                 JOptionPane.showMessageDialog(null, "Ahora sigues a @"+mas.UsuarioBusqueda.getUser());
                 lblFollowers.setText("Followers: "+mas.UsuarioBusqueda.getNumFollowers());
                 lblFollowing.setText("Following: "+mas.UsuarioBusqueda.getNumFollowing());

            }
    }//GEN-LAST:event_SeguirMouseClicked

    private void DejardeSeguirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DejardeSeguirActionPerformed

    }//GEN-LAST:event_DejardeSeguirActionPerformed

    private void DejardeSeguirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DejardeSeguirMouseClicked
        boolean SigueUsuario=false;
        
        for (int i = 0; i < mas.UsuarioActual.getNumFollowing(); i++) {
            if (mas.UsuarioBusqueda.getUser().equals(mas.UsuarioActual.getfollowing()[i])) {
                SigueUsuario=true;
                break;
            }
        }
        
        if(SigueUsuario){
            mas.DejardeSeguir(); 
            JOptionPane.showMessageDialog(null, "Dejaste de Seguir a @"+mas.UsuarioBusqueda.getUser());
            lblFollowers.setText("Followers: "+mas.UsuarioBusqueda.getNumFollowers());
            lblFollowing.setText("Following: "+mas.UsuarioBusqueda.getNumFollowing());  
        }else{

            JOptionPane.showMessageDialog(null, "No sigues a @"+mas.UsuarioBusqueda.getUser());
        }
                
    }//GEN-LAST:event_DejardeSeguirMouseClicked

    private void lblFollowingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFollowingMouseClicked
        new FollowsOtro(mas).setVisible(true);
        this.dispose();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_lblFollowingMouseClicked

    private void lblFollowersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFollowersMouseClicked
        new FollowsOtro(mas).setVisible(true);
        this.dispose();
        this.setLocationRelativeTo(null);
    }//GEN-LAST:event_lblFollowersMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MiPerfil(mas).setVisible(true);
//            }
//        });
//    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DejardeSeguir;
    private javax.swing.JButton Return;
    private javax.swing.JButton Seguir;
    private javax.swing.JTextArea TxtATweets;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFollowers;
    private javax.swing.JLabel lblFollowing;
    private javax.swing.JLabel lblGenAge;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel pfpO;
    // End of variables declaration//GEN-END:variables
}
